___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [4]:
#Creating sample array of numbers from 0 to 10

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
#Get a value at an index 8
arr[8]

8

In [6]:
#Get values in a range --> get 2nd to 5th number in array
arr[1:5]

array([1, 2, 3, 4])

In [7]:
#Get values in a range from 1st to 5th number
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to **broadcast**:

In [5]:
#Setting the 1st 5 values in current array to 100 via the index range = **Broadcasting**
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Important notes on **Slices** --> get 1st 5 numbers from the array
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
#Change each elemen in Slice to 99
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our *original* array!

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [15]:
#To get a **COPY**, need to be EXPLICIT --> SLICES = VIEWS of ORIGINAL ARRAY

arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [16]:
#create matrix of 3 rows and 3 cols

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
#Indexing --> get 2nd row
arr_2d[1]

array([20, 25, 30])

In [16]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value --> 1st element in 2nd row
arr_2d[1][0]

20

In [17]:
# Getting 1st element in 2nd row in a different way
arr_2d[1,0]

20

In [18]:
# 2D array slicing

#Shape (2,2) from top right corner --> get values from 2nd column onward from 1st and 2nd row

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
#Shape bottom row --> get all values from 3rd row
arr_2d[2]

array([35, 40, 45])

In [20]:
#Shape bottom row --> get all values from 3rd row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [19]:
#Set up 10x10 matrix of zeroes
arr2d = np.zeros((10,10))

In [21]:
#get Length of array = how many rows
arr_length = arr2d.shape[1]
arr_length

10

In [22]:
#Set up array --> for each row, set each of the 10 col values in that row equal to the row number

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing allows the following

In [24]:
#get all cols from rows 2,4,6,8
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [25]:
#get all cols from rows 6,4,2,7 *IN ANY ORDER*
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [29]:
#create array from 1-10

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#get a T/F value for each value in the array if its > 4

arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [26]:
#set boolean array into a variable
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [27]:
#get values from original array where boolean array = TRUE

arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
#get values from original array where value > 2

arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#do same thing as above via a variable

x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
