In [2]:
import numpy as np

In [10]:
revenue = np.array([14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97,
                   15433.50]);
expenses = np.array([12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37,
                    3803.96]);

In [13]:
profit = revenue - expenses
profit

array([  2522.67,   1911.39,  -3707.79,  -2914.31,   -599.92,   7265.24,
         8210.55,   3944.97,   3328.39,  -2238.65,    659.6 ,  11629.54])

In [16]:
profitAfterTax = profit - np.round(profit*0.3,2)
profitAfterTax

array([ 1765.87,  1337.97, -2595.45, -2040.02,  -419.94,  5085.67,
        5747.38,  2761.48,  2329.87, -1567.05,   461.72,  8140.68])

In [44]:
AfterTaxProfitMargin = profitAfterTax/revenue
print(AfterTaxProfitMargin)

[ 0.1211617   0.17589917 -0.30139664 -0.22233557 -0.05211047  0.6274391
  0.49993389  0.28276209  0.2260842  -0.10897457  0.04309514  0.52746817]


In [20]:
goodMonths = profitAfterTax > np.mean(profitAfterTax)
goodMonths

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True], dtype=bool)

In [25]:
badMonths = profitAfterTax < np.mean(profitAfterTax)
badMonths

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False], dtype=bool)

In [36]:
bestMonth = np.argmax(profitAfterTax) + 1
worstMonth = np.argmin(profitAfterTax) + 1

bestMonth

12

In [38]:
worstMonth

3

In [47]:
roundProfit = np.round(profit)
roundProfitAfterTax = np.round(profitAfterTax)
AfterTaxProfitMarginPercent = np.round(AfterTaxProfitMargin,2)*100

print(roundProfit)
print(roundProfitAfterTax)
print(AfterTaxProfitMarginPercent)

[  2523.   1911.  -3708.  -2914.   -600.   7265.   8211.   3945.   3328.
  -2239.    660.  11630.]
[ 1766.  1338. -2595. -2040.  -420.  5086.  5747.  2761.  2330. -1567.
   462.  8141.]
[ 12.  18. -30. -22.  -5.  63.  50.  28.  23. -11.   4.  53.]


In [ ]:
#get figures in $1000's of dollars
revenue_1000 = np.round(revenue/1000)
expenses_1000 = np.round(expenses/1000)
profit_1000 = np.round(roundProfit/1000)
profitAfterTax_1000 = np.round(roundProfitAfterTax/1000)

print(revenue_1000)
print(expenses_1000)
print(profit_1000)
print(AfterTaxProfitMarginPercent)
print(profitAfterTax_1000)
print()