* 2D arrays are more memory efficient compared to an array of arrays, and accessing elements are different ( a[1,3] vs. a[1][3] )

In [1]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

print( ridership[1, 3])
print( ridership[1:3, 3:5])
print( ridership[1, :]) # 2nd row

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [2]:
print (ridership[0, :] + ridership[1, :]) # vector math
print( ridership[:, 0] + ridership[:, 1])

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [3]:
# Vectorized operations on entire arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print( a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [37]:
def mean_riders_for_max_station(ridership):
    # Find station with the maximum riders from all days + return the mean riders per day for that station.
    # Return the mean ridership overall for comparison.  
    overall_mean = ridership.mean()
    
    max_col = np.unravel_index(ridership.argmax(), ridership.shape)[1]
    mean_for_max_all = ridership[:,max_col].mean()
    
    # Find station with the maximum riders from FIRST day + return the mean riders per day for that station. Also
    # Return the mean ridership overall for comparison.
    overall_mean_first_day = ridership[0,:].mean()

    mean_for_max_first = ridership[0,np.argmax(ridership[0,:])].mean()
    
    return (overall_mean, mean_for_max_all,overall_mean_first_day,mean_for_max_first)

mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001, 1.3999999999999999, 5.0)

So the station with the most passengers on the first day had a higher overall overage over the 10 days compared to all stations.

In [40]:
def min_and_max_riders_per_day(ridership):
    # For each subway station, calculate the mean ridership per day. 
    mean_rider_per_day = ridership.mean(axis = 0)
    
    #Out of all subway stations, return the maximum and minimum mean values.
    min_daily_ridership = mean_rider_per_day.min()
    max_daily_ridership = mean_rider_per_day.max()
    
    return (max_daily_ridership, min_daily_ridership)

min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)

Can see the max mean and min mean are both where one would expect them to be compared to the overall mean from above

<h1> DataFrames vs. Arrays </h1>

When values are of different types in 2D NumPy Arrays, then each is converted to a string. To keep original data types, use DataFrames

In [42]:
import pandas as pd

# Create a DataFrame out of a dictionary, mapping column names to values ( --> {'col': [value1, value2], 'col2':....})
df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print(df_1)

   A  B
0  0  3
1  1  4
2  2  5


In [43]:
# Can also use a list of lists or a 2D NumPy array
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
print( df_2)

   A  B  C
0  0  1  2
1  3  4  5


In [46]:
# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007'])

# Accessing elements
print( ridership_df.iloc[0]) # 1st row
print( ridership_df.loc['05-05-11']) # row w/ that title
print( ridership_df['R003']) # that column
print( ridership_df.iloc[1, 3]) # specific cell

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64
05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64
2328


In [49]:
# Accessing multiple rows
print( ridership_df.iloc[1:4])
    
# Accessing multiple columns (notice double brackets)
print( ridership_df[['R003', 'R005']])

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [55]:
# Pandas axis
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print( df.sum()) # sums rows + gives an index
print( df.sum(axis=1)) # sums cols + gives an index
print( df.values.sum()) # sum of all numeric values

A     3
B    12
dtype: int64
0    3
1    5
2    7
dtype: int64
15


In [76]:
def mean_riders_for_max_station(ridership):
    # Find station with max riders on 1st day + return mean riders per day for that station. 
    mean_for_max = ridership[[ridership.iloc[0].argmax()]].mean()
    
    # return the mean ridership overall for comparsion.
    overall_mean = ridership.values.mean()
    
    return (overall_mean, mean_for_max)

mean_riders_for_max_station(ridership_df)

(2342.5999999999999, R006    3239.9
 dtype: float64)

<h1>NYC</h1>

In [78]:
nyc = pd.read_csv('nyc_subway_weather.csv')
nyc.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [79]:
nyc.describe()

ENTRIESn        EXITSn  ENTRIESn_hourly  EXITSn_hourly  \
count  4.264900e+04  4.264900e+04     42649.000000   42649.000000   
mean   2.812486e+07  1.986993e+07      1886.589955    1361.487866   
std    3.043607e+07  2.028986e+07      2952.385585    2183.845409   
min    0.000000e+00  0.000000e+00         0.000000       0.000000   
25%    1.039762e+07  7.613712e+06       274.000000     237.000000   
50%    1.818389e+07  1.331609e+07       905.000000     664.000000   
75%    3.263049e+07  2.393771e+07      2255.000000    1537.000000   
max    2.357746e+08  1.493782e+08     32814.000000   34828.000000   

               hour      day_week       weekday      latitude     longitude  \
count  42649.000000  42649.000000  42649.000000  42649.000000  42649.000000   
mean      10.046754      2.905719      0.714436     40.724647    -73.940364   
std        6.938928      2.079231      0.451688      0.071650      0.059713   
min        0.000000      0.000000      0.000000     40.576152    -74.073622   
25%        4.000000      1.000000      0.000000     40.677107    -73.987342   
50%       12.000000      3.000000      1.000000     40.717241    -73.953459   
75%       16.000000      5.000000      1.000000     40.759123    -73.907733   
max       20.000000      6.000000      1.000000     40.889185    -73.755383   

                fog      ...          pressurei          rain         tempi  \
count  42649.000000      ...       42649.000000  42649.000000  42649.000000   
mean       0.009824      ...          29.971096      0.224741     63.103780   
std        0.098631      ...           0.137942      0.417417      8.455597   
min        0.000000      ...          29.550000      0.000000     46.900000   
25%        0.000000      ...          29.890000      0.000000     57.000000   
50%        0.000000      ...          29.960000      0.000000     61.000000   
75%        0.000000      ...          30.060000      0.000000     69.100000   
max        1.000000      ...          30.320000      1.000000     86.000000   

              wspdi   meanprecipi  meanpressurei     meantempi     meanwspdi  \
count  42649.000000  42649.000000   42649.000000  42649.000000  42649.000000   
mean       6.927872      0.004618      29.971096     63.103780      6.927872   
std        4.510178      0.016344       0.131158      6.939011      3.179832   
min        0.000000      0.000000      29.590000     49.400000      0.000000   
25%        4.600000      0.000000      29.913333     58.283333      4.816667   
50%        6.900000      0.000000      29.958000     60.950000      6.166667   
75%        9.200000      0.000000      30.060000     67.466667      8.850000   
max       23.000000      0.157500      30.293333     79.800000     17.083333   

        weather_lat   weather_lon  
count  42649.000000  42649.000000  
mean      40.728555    -73.938693  
std        0.065420      0.059582  
min       40.600204    -74.014870  
25%       40.688591    -73.985130  
50%       40.720570    -73.949150  
75%       40.755226    -73.912033  
max       40.862064    -73.694176  

[8 rows x 21 columns]

In [89]:
import pandas as pd

def correlation(x, y):
    # standardize each value using ddof = 0 to NOT use Bessel's correction for samples
    x_std = (x - x.mean())/x.std(ddof = 0)
    y_std = (y - y.mean())/y.std(ddof = 0)
    
    # Multiply and take average 
    #    - correlation = average of (x in standard units) times (y in standard units)
    r = (x_std*y_std).mean()
    
    return r

entries = nyc['ENTRIESn_hourly']
cum_entries = nyc['ENTRIESn']
rain = nyc['meanprecipi']
temp = nyc['meantempi']

print( correlation(entries, rain))
print (correlation(entries, temp))
print( correlation(rain, temp))
print (correlation(entries, cum_entries))

0.03564851577223041
-0.026693348321569912
-0.22903432340833663
0.5858954707662182


So all have weak correlations, and **entries** and **cumulative entries** have a moderate positive relationship

In [91]:
np.corrcoef(entries,cum_entries)

array([[ 1.        ,  0.58589547],
       [ 0.58589547,  1.        ]])